import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { Itr } from './itr.model';

function inr(value: unknown): string {
  const num = Number(value || 0);
  if (!Number.isFinite(num)) return 'INR 0.00';
  return `INR ${num.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(value: unknown): string {
  if (!value) return 'N/A';
  const dt = new Date(String(value));
  if (Number.isNaN(dt.getTime())) return 'N/A';
  return dt.toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
}

export const itrPdfService = {
  generateSummary(itr: Itr, res: Response) {
    const doc = new PDFDocument({ margin: 50 });

    // Set headers for PDF response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=ITR_Summary_${itr._id}.pdf`);

    doc.pipe(res);

    // Title
    doc.fontSize(25).text('TaxSphere - ITR filing summary', { align: 'center' });
    doc.moveDown();

    // Horizontal Line
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Basic Info
    doc.fontSize(16).text('Individual Information', { underline: true });
    doc.fontSize(12).text(`Name: ${itr.personalInfo?.firstName || '—'} ${itr.personalInfo?.lastName || ''}`);
    doc.text(`PAN: ${itr.personalInfo?.pan || '—'}`);
    doc.text(`Email: ${itr.personalInfo?.email || '—'}`);
    doc.text(`Assessment Year: ${itr.assessmentYear}`);
    doc.text(`Regime: ${itr.regime}`);
    doc.moveDown();

    // Income Table
    doc.fontSize(16).text('Income breakdown', { underline: true });
    doc.fontSize(12).text(`Salary: Rs. ${itr.income?.salary || 0}`);
    doc.text(`Business Income: Rs. ${itr.income?.business || 0}`);
    doc.text(`Capital Gains: Rs. ${itr.income?.capitalGains || 0}`);
    doc.text(`Other Income: Rs. ${itr.income?.otherIncome || 0}`);
    doc.font('Helvetica-Bold').fontSize(14).text(`Total Income: Rs. ${itr.income?.totalIncome || 0}`);
    doc.font('Helvetica');
    doc.moveDown();

    // Deductions Table
    doc.fontSize(16).text('Deductions', { underline: true });
    doc.fontSize(12).text(`Total Deductions applied: Rs. ${itr.deductions?.totalDeductions || 0}`);
    doc.moveDown();

    // Tax Summary
    doc.fontSize(16).text('Tax details', { underline: true });
    doc.fontSize(12).text(`Taxable Income: Rs. ${itr.taxSummary?.taxableIncome || 0}`);
    doc.text(`Rebate 87A: Rs. ${itr.taxSummary?.rebate87A || 0}`);
    doc.text(`Cess: Rs. ${itr.taxSummary?.cess || 0}`);
    doc.font('Helvetica-Bold').fontSize(14).fillColor('red').text(`Final Tax Payable: Rs. ${itr.taxSummary?.finalTax || 0}`);
    doc.font('Helvetica');
    doc.fillColor('black');
    doc.moveDown();

    // Status
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();
    doc.fontSize(14).text(`Current Status: ${itr.status.replace('_', ' ')}`, { align: 'right' });

    // Footer
    doc.fontSize(10).text('Generated by TaxSphere System', { align: 'center', baseline: 'bottom' });

    doc.end();
  },

  generateFiledReturn(itr: Itr, res: Response) {
    const doc = new PDFDocument({ margin: 50 });
    const paymentStatus = String((itr as any).paymentStatus || (itr as any).payment?.paymentStatus || 'not_required').replace(/_/g, ' ');
    const filingStatus = String((itr as any).filingStatus || itr.status || 'draft').replace(/_/g, ' ');
    const filedDate = (itr as any).filedAt || null;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="TaxSphere_ITR_${itr._id}.pdf"`);
    doc.pipe(res);

    doc.font('Helvetica-Bold').fontSize(20).text('TaxSphere', { align: 'center' });
    doc.font('Helvetica').fontSize(12).text('ITR Filing Summary', { align: 'center' });
    doc.moveDown(1.2);

    doc.font('Helvetica-Bold').fontSize(12).text(`ITR ID: ${String(itr._id)}`);
    doc.font('Helvetica').fontSize(11).text(`Generated At: ${fmtDate(new Date())}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(13).text('User Details');
    doc.font('Helvetica').fontSize(11).text(`Name: ${itr.personalInfo?.firstName || 'N/A'} ${itr.personalInfo?.lastName || ''}`.trim());
    doc.text(`Email: ${itr.personalInfo?.email || 'N/A'}`);
    doc.text(`PAN: ${itr.personalInfo?.pan || 'N/A'}`);
    doc.text(`Mobile: ${itr.personalInfo?.mobile || 'N/A'}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(13).text('ITR Meta');
    doc.font('Helvetica').fontSize(11).text(`Assessment Year: ${itr.assessmentYear || 'N/A'}`);
    doc.text(`Financial Year: ${itr.financialYear || 'N/A'}`);
    doc.text(`Regime: ${itr.regime || 'N/A'}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(13).text('Income Details');
    doc.font('Helvetica').fontSize(11).text(`Salary: ${inr((itr as any).income?.salary)}`);
    doc.text(`Business: ${inr((itr as any).income?.business)}`);
    doc.text(`Capital Gains: ${inr((itr as any).income?.capitalGains)}`);
    doc.text(`Other Income: ${inr((itr as any).income?.otherIncome)}`);
    doc.font('Helvetica-Bold').text(`Total Income: ${inr((itr as any).income?.totalIncome)}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(13).text('Deduction Details');
    doc.font('Helvetica').fontSize(11).text(`80C: ${inr((itr as any).deductions?.c80C)}`);
    doc.text(`80D: ${inr((itr as any).deductions?.c80D)}`);
    doc.text(`80E: ${inr((itr as any).deductions?.c80E)}`);
    doc.text(`80G: ${inr((itr as any).deductions?.c80G)}`);
    doc.text(`NPS: ${inr((itr as any).deductions?.nps)}`);
    doc.font('Helvetica-Bold').text(`Total Deductions: ${inr((itr as any).deductions?.totalDeductions)}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(13).text('Tax Calculation Summary');
    doc.font('Helvetica').fontSize(11).text(`Taxable Income: ${inr((itr as any).taxSummary?.taxableIncome)}`);
    doc.text(`Tax Before Rebate: ${inr((itr as any).taxSummary?.taxBeforeRebate)}`);
    doc.text(`Rebate 87A: ${inr((itr as any).taxSummary?.rebate87A)}`);
    doc.text(`Cess: ${inr((itr as any).taxSummary?.cess)}`);
    doc.font('Helvetica-Bold').text(`Final Tax: ${inr((itr as any).taxSummary?.finalTax)}`);
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(13).text('Payment And Filing');
    doc.font('Helvetica').fontSize(11).text(`Payment Status: ${paymentStatus}`);
    doc.text(`Filing Status: ${filingStatus}`);
    doc.text(`Filed Date: ${filedDate ? fmtDate(filedDate) : 'Pending final filing'}`);
    doc.text(`CA Remarks: ${(itr as any).caRemarks ? String((itr as any).caRemarks) : 'N/A'}`);
    doc.moveDown();

    doc.font('Helvetica-Oblique').fontSize(10).text('System-generated document from TaxSphere. This PDF is generated for record and reference purposes.', {
      align: 'left',
    });

    doc.end();
  },
};
